services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      METEOR_SECRETS_BOT_TOKEN: ""
      METEOR_SECRETS_DATABASE_HOST: postgres
      METEOR_SECRETS_DATABASE_PORT: 5432
      METEOR_SECRETS_DATABASE_USERNAME: postgres
      METEOR_SECRETS_DATABASE_PASSWORD: postgres
      METEOR_SECRETS_DATABASE_NAME: meteor
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "grep", "docker-ok", "/app/logs/app.log" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meteor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
